import {createElement} from './elementCreator'

export default function aboutTab(content) {
  content.appendChild(createElement('h1', 'A Little Bit About Us'));
  content.appendChild(createElement('p', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Pulvinar sapien et ligula ullamcorper malesuada proin. Nec sagittis aliquam malesuada bibendum arcu vitae. Et leo duis ut diam quam nulla porttitor massa id. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Pharetra massa massa ultricies mi quis hendrerit dolor magna. Nibh tellus molestie nunc non blandit massa enim nec dui.'));
  content.appendChild(createElement('p', 'Nulla porttitor massa id neque aliquam. Rutrum quisque non tellus orci ac. Eget duis at tellus at urna. Eget dolor morbi non arcu risus quis. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Suspendisse in est ante in nibh mauris. Tristique senectus et netus et. Sed vulputate odio ut enim blandit volutpat. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Sed turpis tincidunt id aliquet. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Quisque non tellus orci ac auctor augue.'));
  content.appendChild(createElement('p', 'Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Porttitor lacus luctus accumsan tortor posuere ac ut. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Sit amet nisl purus in mollis nunc sed id semper. Venenatis urna cursus eget nunc. Curabitur vitae nunc sed velit. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Volutpat lacus laoreet non curabitur gravida. Neque egestas congue quisque egestas. Nisi scelerisque eu ultrices vitae. Fames ac turpis egestas maecenas pharetra. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Elit ut aliquam purus sit amet luctus venenatis.'));
  content.appendChild(createElement('p', 'Mi in nulla posuere sollicitudin aliquam. Massa enim nec dui nunc mattis enim. Id eu nisl nunc mi. Quis viverra nibh cras pulvinar. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Hendrerit dolor magna eget est. Adipiscing enim eu turpis egestas pretium. Libero nunc consequat interdum varius sit. Facilisis sed odio morbi quis commodo odio. Proin nibh nisl condimentum id. Tristique nulla aliquet enim tortor at auctor. Amet aliquam id diam maecenas ultricies mi eget mauris. Facilisis volutpat est velit egestas dui. Feugiat nibh sed pulvinar proin.'));
  content.appendChild(createElement('p', 'Aliquam etiam erat velit scelerisque in dictum non consectetur. Consectetur adipiscing elit duis tristique sollicitudin nibh. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Massa massa ultricies mi quis hendrerit dolor magna eget. Tristique senectus et netus et malesuada fames ac. Posuere ac ut consequat semper viverra nam libero. Bibendum at varius vel pharetra vel turpis. Sed enim ut sem viverra aliquet eget sit amet. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Vitae semper quis lectus nulla at.' ))
}